language: python
cache: pip
dist: xenial

env:
  TOXENV=py

jobs:
  include:
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.7"
    python: 3.7
  - name: "run test suite with python 3.8"
    python: 3.8
  - name: "type check"
    python: 3.7
    env:
    - TOXENV=type
  - name: "check code style with flake8"
    python: 3.7
    env:
    - TOXENV=lint

install:
- pip install -U pip setuptools
- pip install -U 'virtualenv<20'
- pip install -U tox==3.9.0
- tox --notest

script:
  tox
